### ISSUE TITLE
Demo request: LED light circle in rippled water

### ISSUE THREAD

**Issue by sw3d2** [apbodnar/FSPT#3]
This is some jaw dropping render quality here. Thanks for sharing this work.

I had in mind one idea that boils down to raytracing a LED-ring in rippled water. I see one example renders a sophisticated surface of a face, and water with ripples can be represented as a mesh with some Bezier-style smoothing technique. The remaining part is modeling reflections and refractions with sufficient depth and quality. Is it something that's supported already?

**Comment by apbodnar** [comment]
Thanks for the request.  Unfortunately, I decided to remove refraction a while back while i was re-implementing the BRDF and material logic.  I simply haven't rushed to support it again since it's basically brute force Monte Carlo, but I'll be making it a priority now!  Also, do you picture the LED ring being submerged in the water and viewed from above the surface?

**Comment by sw3d2** [comment]
The ring should be above the water as the goal is to capture the reflections. It's like the Moon's reflection in a lake, except that we replace the Moon with a LED light ring 10 cm above a small round dish with water simulating the lake. If the water surface is rippled in a symmetric way, the reflections will form a very curious pattern. This is how you get the so called [cymaglyphs](https://www.cymascope.com/cyma_research/images/pianonotes.jpg) - a small petri dish with water vibrates with some frequency, so the water surface assumes the shape of one of those [laplacian eigenfunctions](https://www.chebfun.org/examples/disk/Eigenfunctions.html), and the reflection of the light ring above forms the pattern (if the water was still or the liquid was non transparent or didn't have refraction, the pattern would be rather dull). Whether the semi-transparent petri dish contributes to the captured picture is a question, but my guess is that it's not a significant contributor.

Example of eigenfunctions (the water surface height map):

![](https://www.chebfun.org/examples/disk/img/Eigenfunctions_05.png)

Example of reflections of a light ring in those surfaces:

![](https://www.cymascope.com/cyma_research/images/pianonotes.jpg)

Some people experimented with a few colored light rings to get more sophisticated reflections.

One additional observation is that refraction depends on the light wave length: a red light ring would form a different pattern than a green one. But that should be easy to simulate, as in the worst case we can just render two scenes with different refraction settings and overlay the results. Rendering a continuous spectrum light would be challenge, though.

**Comment by apbodnar** [comment]
This all seems doable. I've been meaning to write a tool that discretizes 3d surfaces as meshes anyways.  One concern is this will probably take a long time to converge. When we shoot a ray into a refractive medium we lose some optimizations because we no longer know how to directly sample the lights; we instead have to rely on (almost) brute force sampling and hoping we hit a light or refract back into a space that can directly sample a light.  Since presumably a ring of LEDs has very small light sources, the probably of randomly refracting from the bottom of this petri dish back to an LED is extremely small.

**Comment by sw3d2** [comment]
Generating the mesh can be left to the user, as long as the renderer understands that the mesh needs to be accurately interpolated for smoothness.

That problem with low probabilities is likely unavoidable: due to the complexity of the surfaces in question, it seems a research problem whether such optimizations are possible. I'd make a guess that something like "differential path tracing" is a part of the answer: since those surfaces are generally smooth, a slight change in the ray direction changes the result only slightly, except when it crosses a boundary of a surface.

Another problem is that if it takes on average 10 reflections or refractions to connect the light source with the camera, the probability to find such a ray drops exponentially, while the accuracy error adds up linearly. I suspect that the high number of inter-reflections is what makes the pictures above so sophisticated. 

But regardless, it would be cool to have a bruteforce refraction algorithm - at least it would be something to experiment with.

**Comment by apbodnar** [comment]
![download (25)](https://user-images.githubusercontent.com/2200441/80686537-b165b800-8a7d-11ea-8c0c-7092961a0b67.png)

A quick preview of a hacked together re-addition of refraction.  I'll do a cleanup pass and add some Beer's law effects and push up soon :)

**Comment by sw3d2** [comment]
Ship it :)

**Comment by apbodnar** [comment]
Refraction is now re-added. I'll work on adding better documentation this weekend.
